### ISSUE TITLE
You might have a look into unshell :)

### ISSUE THREAD

**Issue by romainPrignon** [antonmedv/tinysh#3]
https://github.com/romainPrignon/unshell-deno

**Comment by antonmedv** [comment]
Take a look at google/zx ;)

**Comment by romainPrignon** [comment]
Hey
My message was too succinct.
I know about zx, I use it a lot. Thanks for making it.
I just wanted to let you know that we might try to achieve the same thing with unshell or tinysh. You might find goods (or bad!) idea inside unshell if you want to have a look

**Comment by antonmedv** [comment]
Is it related to https://www.npmjs.com/package/unshell?

**Comment by antonmedv** [comment]
Why port to deno?)

**Comment by romainPrignon** [comment]
yes, but unshell is an old idea.
unshell-deno is a new attempt. In the spirit of tinysh.

I choose deno because:
- it can be easily port to node
- there is no need to import the library (unshell) before using it. Like doing a curl script.sh | bash or runner remote script in zx. Everything can be "on the fly". 
- deno gives better guarantees with the `--allow-run` `--allow-env` to control what's being run
